### ISSUE TITLE
Unable to verify items identifier in api calls

### ISSUE THREAD

**Issue by jeferson-sb** [LauraBeatris/use-selected-items-hook#1]
## Description
When you fetch for items in a api call, it throws an error `Please, make sure to provide a valid identifier`
I was searching about it, and I noticed it's because when the application loads the items are an empty array, so the library cannot find the `id`

Great library by the way @LauraBeatris! 

## How to Reproduce
Access : [this sandbox](https://codesandbox.io/s/experimeting-use-selected-items-hook-7z168?file=/src/App.tsx)

## Package version
1.0.6

## Node version
12.18.2

## React Version
16.12.0

**Comment by LauraBeatris** [comment]
Thanks for creating this issue! I'll be working to fix it

**Comment by LauraBeatris** [comment]
@jeferson-sb The release 1.0.7 was launched and now the hook has support for items being set asynchronously or initialized as falsy values

Thanks for your contribution!
